server:
    port: 8080
    servlet:
        session:
            timeout: 21600
spring:
    application:
        name: microblog
    servlet:
        multipart:
            max-file-size: 8MB
            max-request-size: 40MB
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/microblog?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: root
        password: blog#123
        hikari:
            minimum-idle: 5
            idle-timeout: 180000
            maximum-pool-size: 10
            auto-commit: true
            pool-name: MyHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
    elasticsearch:
        rest:
            uris: http://127.0.0.1:9200
            username: elastic
            password: elastic
            read-timeout: 10s
            connection-timeout: 5s
    mail:
        test-connection: true
        host: 邮箱平台smtp服务器地址
        port: 587
        nickname: 发送邮件时的昵称
        username: 发送邮件的邮箱
        password: 邮箱平台的授权码
        default-encoding: UTF-8
        protocol: smtp
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls:
                        enable: true
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: blog_manager
        password: blog_manager
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3 #最大重试次数
                    initial-interval: 10000 #重试间隔时间（单位毫秒）
    redis:
        host: 127.0.0.1
        port: 6379
        password: blog123
        database: 2
management:
    health:
        elasticsearch:
            enabled: true
        mail:
            enabled: true
logging:
    file:
        path: ./log/${spring.application.name}/
    level:
        root: info
        com:
            yinghuomars:
                microblog: trace
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    global-config:
        banner: false
yinghuomars:
    # 网站域名（邮件通知用）
    website:
        url: http://127.0.0.1:8080
    upload:
        # 上传策略 可选local或oss
        mode: local
        local:
            base-url: http://127.0.0.1:8080:8080/static/
            base-path: D:/mars-microblog/static/
    swagger:
        basic:
            host: http://127.0.0.1:8080/
            title: YINGHUOMARS-BLOG
            description: ${yinghuomars.swagger.basic.title} API DOC
    search:
        # 搜索模式 可选 elasticsearch或mysql
        mode: elasticsearch
    # 第三方配置信息
    platform:
        # qq开放平台
        qq:
            app-id: QQ APPID
            check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
            user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}
        # 微博开放平台
        weibo:
            app-id: 微博APPID
            app-secret: 微博APPSECRET
            grant-type: authorization_code
            redirect-url: 微博回调地址
            access-token-url: https://api.weibo.com/oauth2/access_token
            user-info-url: https://api.weibo.com/2/users/show.json?uid={uid}&access_token={access_token}