server:
    port: 8080
    servlet:
        session:
            timeout: 21600
spring:
    application:
        name: yinghuomars-blog
    servlet:
        multipart:
            max-file-size: ${MULT_MAX_SIZE:5MB}
            max-request-size: ${MULT_MAX_REQ:20MB}
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DATABASE_HOST:127.0.0.1}:${DATABASE_PORT:3306}/${DATABASE_DB:microblog}?useUnicode=true&characterEncodeing=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
        username: ${DATABASE_USERNAME:root}
        password: ${DATABASE_PASSWORD:Blog123@mysql}
        hikari:
            minimum-idle: 5
            idle-timeout: 180000
            maximum-pool-size: 10
            auto-commit: true
            pool-name: MyHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
    elasticsearch:
        rest:
            uris: ${ES_URI:http://127.0.0.1:9200}
            username: ${ES_USERNAME:elastic}
            password: ${ES_PASSWORD:Blog123@elastic}
            read-timeout: ${ES_READ_TIMEOUT:10s}
            connection-timeout: ${ES_CONN_TIMEOUT:5s}
    mail:
        test-connection: ${MAIL_TEST:true}
        host: ${MAIL_HOST:smtp.qq.com}
        port: ${MAIL_PORT:587}
        nickname: ${MAIL_NICKNAME:荧惑Mars}
        username: ${MAIL_USERNAME:admin@qq.com}
        password: ${MAIL_PASSWORD:''}
        default-encoding: UTF-8
        protocol: smtp
        properties:
            mail:
                transport:
                    protocol: smtp
                smtp:
                    auth: true
                    starttls:
                        enable: true
    rabbitmq:
        host: ${RABBITMQ_HOST:127.0.0.1}
        port: ${RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:admin}
        password: ${RABBITMQ_PASSWORD:Blog123@rabbitmq}
        listener:
            simple:
                retry:
                    enabled: true
                    max-attempts: 3 #最大重试次数
                    initial-interval: 5000 #重试间隔时间（单位毫秒）
    redis:
        host: ${REDIS_HOST:127.0.0.1}
        port: ${REDIS_PORT:5672}
        password: ${REDIS_PWD:admin}
        database: ${REDIS_DATABASE:Blog123@redis}
management:
    health:
        elasticsearch:
            enabled: ${MANAGE_HEALTH_ES:true}
        mail:
            enabled: ${MANAGE_HEALTH_MAIL:true}
logging:
    file:
        path: /home/log/${spring.application.name}/
    level:
        root: info
        com:
            yinghuomars:
                microblog: info
mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    global-config:
        banner: false
yinghuomars:
    # 网站域名（邮件通知用）
    website:
        url: ${WEBSITE_URL:http://localhost}
    upload:
        # 上传策略 可选local或oss
        mode: ${UPLOAD_MODE:local}
        local:
            base-url: ${UPLOAD_LOCAL_BASEURL:http://127.0.0.1/static/}
            base-path: ${UPLOAD_LOCAL_BASEPATH:/home/static/}
        oss:
            url: ${UPLOAD_OSS_URL:''}
            access-key-id: ${UPLOAD_OSS_ACCESS_ID:''}
            access-key-secret: ${UPLOAD_OSS_ACCESS_SECRET:''}
            endpoint: ${UPLOAD_OSS_ENDPOINT:''}
            bucket-name: ${UPLOAD_OSS_BUCKET:''}
    search:
        # 搜索模式 可选 elasticsearch或mysql
        mode: ${SEARCH_MODE:mysql}
    # 第三方配置信息
    platform:
        # qq开放平台
        qq:
            app-id: ${PLATFORM_QQ_APPID:''}
            check-token-url: https://graph.qq.com/oauth2.0/me?access_token={access_token}
            user-info-url: https://graph.qq.com/user/get_user_info?openid={openid}&access_token={access_token}&oauth_consumer_key={oauth_consumer_key}